In [1]:
import pandas as pd
import plotly.express as px
import numpy as np

In [2]:
filename = "shopping_behavior.csv"
df = pd.read_csv(filename)

In [3]:
df.head(1)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly

In [4]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df_age_gender = df.groupby(['Gender','Age'])['Age'].value_counts().reset_index()
df_age_gender.head(1)
df_age_gender.to_csv("df_age_gender.csv")

In [7]:
fig = px.bar(
    df_age_gender,
    x='Age',
    y='count',
    color='Gender',
    barmode = 'relative'
)
fig.show()

In [8]:
gender_category_df = df.groupby(['Gender', 'Category'])['Category'].value_counts().reset_index()
gender_category_df.to_csv('gender_category_df.csv')

In [9]:
gender_category_df

   Gender     Category  count
0  Female  Accessories    392
1  Female     Clothing    556
2  Female     Footwear    199
3  Female    Outerwear    101
4    Male  Accessories    848
5    Male     Clothing   1181
6    Male     Footwear    400
7    Male    Outerwear    223

In [10]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [11]:
category_items_df = df.groupby(['Item Purchased', 'Category'])['Item Purchased'].value_counts().reset_index()
category_items_df.head()

  Item Purchased     Category  count
0       Backpack  Accessories    143
1           Belt  Accessories    161
2         Blouse     Clothing    171
3          Boots     Footwear    144
4           Coat    Outerwear    161

In [12]:
category_items_df.to_csv("category_items_df.csv")

In [13]:
seasonal_purchase_behaviour_df = df.groupby(['Item Purchased','Gender','Season'])['Season'].value_counts().reset_index()
seasonal_purchase_behaviour_df.head()

  Item Purchased  Gender  Season  count
0       Backpack  Female    Fall      8
1       Backpack  Female  Spring      8
2       Backpack  Female  Summer     15
3       Backpack  Female  Winter      6
4       Backpack    Male    Fall     26

In [14]:
seasonal_purchase_behaviour_df.to_csv('seasonal_purchase_behaviour_df.csv')

In [15]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [16]:
purchase_frequency_df = df.groupby(['Frequency of Purchases','Gender'])['Frequency of Purchases'].value_counts().reset_index()

In [17]:
purchase_frequency_df.head(6)

  Frequency of Purchases  Gender  count
0               Annually  Female    185
1               Annually    Male    387
2              Bi-Weekly  Female    188
3              Bi-Weekly    Male    359
4         Every 3 Months  Female    186
5         Every 3 Months    Male    398

In [18]:
frequency_avg = purchase_frequency_df.groupby('Gender')['count'].mean().reset_index()
frequency_avg.to_csv('purchase_frequency_avg.csv')

In [19]:
item_frequency = df.groupby(['Item Purchased','Gender','Frequency of Purchases'])['Item Purchased'].value_counts().reset_index(name='frequency')
item_frequency.head(6)

  Item Purchased  Gender Frequency of Purchases  frequency
0       Backpack  Female               Annually          5
1       Backpack  Female              Bi-Weekly          5
2       Backpack  Female         Every 3 Months          8
3       Backpack  Female            Fortnightly          5
4       Backpack  Female                Monthly          1
5       Backpack  Female              Quarterly          6

In [20]:
item_frequency.shape

(350, 4)

In [21]:
df['Frequency of Purchases'].value_counts()

Frequency of Purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [22]:
item_above_median = item_frequency[item_frequency['frequency'] >= item_frequency['frequency'].median()]
item_above_median.to_csv('item_above_median.csv')
item_below_median = item_frequency[item_frequency['frequency'] < item_frequency['frequency'].median()]
item_below_median.to_csv('item_below_median.csv')

In [23]:
weekly_df = item_frequency[item_frequency['Frequency of Purchases'] == 'Weekly']

peaks_frequently_bought_items_weekly = weekly_df[
    (weekly_df['frequency'] == weekly_df['frequency'].max()) |
    (weekly_df['frequency'] == weekly_df['frequency'].min())
]
peaks_frequently_bought_items_weekly

    Item Purchased  Gender Frequency of Purchases  frequency
160          Jeans  Female                 Weekly          2
335        Sweater    Male                 Weekly         22

In [24]:
purchase_frequency_dataframes = []
indices = [j for j in range(0,7)]
frequency_of_purchase = df['Frequency of Purchases'].unique().tolist()
for freq,i in zip(frequency_of_purchase,indices):
    temp_df = item_frequency[item_frequency['Frequency of Purchases'] == freq]

    peaks_freq = temp_df[
        (temp_df['frequency'] == temp_df['frequency'].max()) |
        (temp_df['frequency'] == temp_df['frequency'].min())
    ]

    purchase_frequency_dataframes.append(peaks_freq)

In [25]:
purchase_frequency_dataframes

[    Item Purchased  Gender Frequency of Purchases  frequency
 73           Dress  Female            Fortnightly          2
 332        Sweater    Male            Fortnightly         21,
     Item Purchased  Gender Frequency of Purchases  frequency
 160          Jeans  Female                 Weekly          2
 335        Sweater    Male                 Weekly         22,
     Item Purchased  Gender Frequency of Purchases  frequency
 154          Jeans  Female               Annually          2
 231          Shirt    Male               Annually         24,
     Item Purchased  Gender Frequency of Purchases  frequency
 159          Jeans  Female              Quarterly          2
 320     Sunglasses    Male              Quarterly         24,
     Item Purchased  Gender Frequency of Purchases  frequency
 155          Jeans  Female              Bi-Weekly          3
 176        Jewelry    Male              Bi-Weekly         25
 281       Sneakers  Female              Bi-Weekly          3,
     Item Purchased  Gender Frequency of Purchases  frequency
 4         Backpack  Female                Monthly          1
 193          Pants    Male                Monthly         22,
     Item Purchased  Gender Frequency of Purchases  frequency
 86          Gloves  Female         Every 3 Months          2
 191          Pants    Male         Every 3 Months         22]

In [26]:
freq_df = pd.concat(
    purchase_frequency_dataframes,
    ignore_index=True
)[
    ['Frequency of Purchases', 'Item Purchased', 'Gender', 'frequency']
]

freq_df.to_csv('freq_df.csv')

In [27]:
# products bought by females
female = item_frequency[item_frequency['Gender'] == 'Female']
female

    Item Purchased  Gender Frequency of Purchases  frequency
0         Backpack  Female               Annually          5
1         Backpack  Female              Bi-Weekly          5
2         Backpack  Female         Every 3 Months          8
3         Backpack  Female            Fortnightly          5
4         Backpack  Female                Monthly          1
..             ...     ...                    ...        ...
338        T-shirt  Female         Every 3 Months          8
339        T-shirt  Female            Fortnightly          6
340        T-shirt  Female                Monthly          8
341        T-shirt  Female              Quarterly          4
342        T-shirt  Female                 Weekly          6

[175 rows x 4 columns]

In [28]:
freq_bought_by_female = female[female['frequency'] >= 10]
freq_bought_by_female.to_csv('freq_female.csv')

In [29]:
male = item_frequency[item_frequency['Gender'] == 'Male']
male

    Item Purchased Gender Frequency of Purchases  frequency
7         Backpack   Male               Annually         17
8         Backpack   Male              Bi-Weekly         16
9         Backpack   Male         Every 3 Months         15
10        Backpack   Male            Fortnightly         17
11        Backpack   Male                Monthly         10
..             ...    ...                    ...        ...
345        T-shirt   Male         Every 3 Months         18
346        T-shirt   Male            Fortnightly         13
347        T-shirt   Male                Monthly         14
348        T-shirt   Male              Quarterly         18
349        T-shirt   Male                 Weekly         13

[175 rows x 4 columns]

In [30]:
freq_bought_by_male = male[male['frequency'] > male['frequency'].median()]
freq_bought_by_male.to_csv('freq_male.csv')

In [31]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [32]:
season_category_freq = df.groupby(['Category','Season','Gender'])['Category'].value_counts().reset_index(name='frequency')
season_category_freq.head()

      Category  Season  Gender  frequency
0  Accessories    Fall  Female        110
1  Accessories    Fall    Male        214
2  Accessories  Spring  Female         85
3  Accessories  Spring    Male        216
4  Accessories  Summer  Female        100

In [33]:
season_category_freq[season_category_freq['Gender'] == 'Male']

       Category  Season Gender  frequency
1   Accessories    Fall   Male        214
3   Accessories  Spring   Male        216
5   Accessories  Summer   Male        212
7   Accessories  Winter   Male        206
9      Clothing    Fall   Male        275
11     Clothing  Spring   Male        318
13     Clothing  Summer   Male        282
15     Clothing  Winter   Male        306
17     Footwear    Fall   Male         95
19     Footwear  Spring   Male         97
21     Footwear  Summer   Male        113
23     Footwear  Winter   Male         95
25    Outerwear    Fall   Male         63
27    Outerwear  Spring   Male         52
29    Outerwear  Summer   Male         50
31    Outerwear  Winter   Male         58

In [34]:
male_season = season_category_freq[season_category_freq['Gender'] == 'Male']
female_season = season_category_freq[season_category_freq['Gender'] == 'Female']

In [35]:
season_category_freq.to_csv('season_category_freq.csv')

In [36]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [37]:
# purchase amount analysis
purchase_amt = df.groupby(['Gender','Category','Payment Method'])['Purchase Amount (USD)'].mean().reset_index(name="Amount")
purchase_amt.to_csv('purchase_amt.csv')

In [41]:
freq_bought_by_female.head()

   Item Purchased  Gender Frequency of Purchases  frequency
18           Belt  Female                Monthly         13
28         Blouse  Female               Annually         13
29         Blouse  Female              Bi-Weekly         14
30         Blouse  Female         Every 3 Months         14
45          Boots  Female            Fortnightly         10

In [49]:
female_items = freq_bought_by_female.groupby(['Item Purchased','Gender'])['frequency'].sum().reset_index(name='frequency')
female_items['probability'] = female_items['frequency']/female_items['frequency'].sum()
female_items.head()

  Item Purchased  Gender  frequency  probability
0           Belt  Female         13     0.039514
1         Blouse  Female         41     0.124620
2          Boots  Female         22     0.066869
3          Dress  Female         30     0.091185
4        Handbag  Female         33     0.100304

In [50]:
male_items = freq_bought_by_male.groupby(['Item Purchased','Gender'])['frequency'].sum().reset_index(name='frequency')
male_items['probability'] = male_items['frequency']/male_items['frequency'].sum()
male_items.head()

  Item Purchased Gender  frequency  probability
0       Backpack   Male         66     0.045549
1           Belt   Male         53     0.036577
2         Blouse   Male         88     0.060732
3          Boots   Male         35     0.024155
4           Coat   Male         59     0.040718

In [51]:
female_items.to_csv('female_items_prob.csv')
male_items.to_csv('male_items_prob.csv')